"""Initial migration

Revision ID: 8d919a211e93
Revises: 
Create Date: 2025-03-07 05:19:59.735278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d919a211e93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('custom_id', sa.String(length=50), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('custom_id')
    )
    op.create_table('users',
    sa.Column('custom_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('custom_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contacts',
    sa.Column('custom_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('contact_user_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['contact_user_id'], ['users.custom_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.custom_id'], ),
    sa.PrimaryKeyConstraint('custom_id')
    )
    op.create_table('group_members',
    sa.Column('custom_id', sa.String(length=50), nullable=False),
    sa.Column('group_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.custom_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.custom_id'], ),
    sa.PrimaryKeyConstraint('custom_id')
    )
    op.create_table('messages',
    sa.Column('custom_id', sa.String(length=50), nullable=False),
    sa.Column('sender_id', sa.String(length=50), nullable=True),
    sa.Column('receiver_id', sa.String(length=50), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.custom_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.custom_id'], ),
    sa.PrimaryKeyConstraint('custom_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('group_members')
    op.drop_table('contacts')
    op.drop_table('users')
    op.drop_table('groups')
    # ### end Alembic commands ###
