"""Remove CASCADE and add triggers

Revision ID: c039e28897b4
Revises: 
Create Date: 2025-03-13 21:50:38.118647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c039e28897b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('custom_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('custom_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_is_blocked'), ['is_blocked'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_online'), ['is_online'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('contacts',
    sa.Column('custom_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('contact_user_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['contact_user_id'], ['users.custom_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.custom_id'], ),
    sa.PrimaryKeyConstraint('custom_id'),
    sa.UniqueConstraint('user_id', 'contact_user_id', name='uq_contact')
    )
    op.create_table('friendrequest',
    sa.Column('custom_id', sa.String(length=50), nullable=False),
    sa.Column('sender_id', sa.String(length=50), nullable=False),
    sa.Column('receiver_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.custom_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.custom_id'], ),
    sa.PrimaryKeyConstraint('custom_id'),
    sa.UniqueConstraint('sender_id', 'receiver_id', name='uq_friend_request')
    )
    op.create_table('groups',
    sa.Column('custom_id', sa.String(length=50), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.custom_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('custom_id')
    )
    op.create_table('messages',
    sa.Column('custom_id', sa.String(length=50), nullable=False),
    sa.Column('sender_id', sa.String(length=50), nullable=False),
    sa.Column('receiver_id', sa.String(length=50), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.custom_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.custom_id'], ),
    sa.PrimaryKeyConstraint('custom_id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_timestamp'), ['timestamp'], unique=False)

    op.create_table('groupmembers',
    sa.Column('group_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.custom_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.custom_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_member')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groupmembers')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_timestamp'))

    op.drop_table('messages')
    op.drop_table('groups')
    op.drop_table('friendrequest')
    op.drop_table('contacts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_is_online'))
        batch_op.drop_index(batch_op.f('ix_users_is_blocked'))

    op.drop_table('users')
    # ### end Alembic commands ###
