"""empty message

Revision ID: c9cb59d6c552
Revises: c039e28897b4
Create Date: 2025-03-14 19:01:44.434902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9cb59d6c552'
down_revision = 'c039e28897b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_messages_is_read'), ['is_read'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_is_read'))
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
